name: buildtest
on: 
  push:
    branches:
      - master

    tags:
      - *

jobs:
  runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      -
        uses: docker/login-action@v1
        name: Login to GitHub Container Registry
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: build 
        run:
          docker build -t ghcr.io/sai-lab/hello:${{ github.ref }}
      - name: push
        run: 
          docker push ghcr.io/sai-lab/hello:${{ github.ref }}

