name: 
on:
  push:
    tags:
      - '*'
jobs:
  make:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set environment
        shell: bash
        run: echo "::set-env name=VERSION::$( echo ${GITHUB_REF:10})"
      - name: gorev
        run: |
          GOPROXY=https://proxy.golang.org 
          GO111MODULE=on go get github.com/sai_lab/go-template@$VERSION

