name: Vulnerability Scanning
on: [pull_request]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        name: Login to GitHub Container Registry
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Set environment
        shell: bash
        run: echo "::set-env name=VERSION::$( echo ${GITHUB_REF:10})"

      - name: Build an image from Dockerfile
        run: 
          docker build -t ghcr.io/sai-lab/hello:$VERSION .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/sai-lab/hello:$VERSION'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          #severity: 'CRITICAL,HIGH'
