name: Velnerability Scanning
on: [pull_request]

jobs:
  scan:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build an image from Dockerfile
      run: docker build -t ${{ github.repository }} .

    - name: Run Trivy  vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '${{ github.repository }}'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        severity: 'CRITICAL,HIGH'
