name: Velnerability Scanning
on: [pull_request,push]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build an image from Dockerfile
      run: docker build -t ${{ github.repository }} .

    - name: Run Trivy  vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '${{ github.repository }}'
        format: 'json'
        output: 'out'
        exit-code: '1'
        ignore-unfixd: true
        #severity: 'CRITICAL,HIGH'

    - name: Comment to Pull requests
      uses: actions/github-script@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { issue: { number: issue_number }, repo: { owner, repo }  } = context;
          github.issues.createComment({ issue_number, owner, repo, body: out }); 
